### ISSUE TITLE
Popup: Guardar-Editar relación ManyToMany

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#100]
En los popups, no se guardan-modifican los campos con relaciones ManyToMany. Los campos de este tipo tengo salvarlos manualmente sobreescribiendo el código.

**Comment by axelhzf** [comment]
El problema ya debería estar solucionado con este commit cd0faa9c25d4bb1e7dbf91b202c0dcbf0041cf98
