### ISSUE TITLE
Correo de Soporte

### ISSUE THREAD

**Issue by jlucasgl** [FAP-Team/Fap-Module#103]
Hola,

Tenemos una duda con el tema del formulario de soporte que no sabía resolver consultando la documentación. ¿ Fap incluye algún gestor de e-mails ? ¿ Como se reciben los mensajes que han sido enviados mediante este formulario ?

**Comment by axelhzf** [comment]
La página de Soporte tiene el código:

``` java
    emails.Mails.enviar("incidencia",incidencia);
```

Esto quiere decir que se está enviando el email con id "incidencia" y se le esta pasando un objeto de tipo incidencia que contiene los valores rellenados por el usuario.

``` javascript
Entidad Incidencia {
    Email email
    String telefono
    String nombre
    String apellidos
    String asunto
    LongText texto
}
```

Para gestionar los emails tienes una página en administración [http://localhost:9000/Administracion/emails]()
Ahí tienes que definir un email con id "incidencia" y poner el contenido que quieres que tenga y a donde se tiene que enviar el correo. Como pone en el popup puedes utilizar ${} para hacer sustitución de variables.

También tienes que definir la configuración del servidor de correo que vas a utilizar en el `application.conf`

``` ini
mail.smtp.host=undefined.com
mail.smtp.user=undefined
mail.smtp.pass=undefined
mail.smtp.port=25
```
