### ISSUE TITLE
Guardar lista múltiple en una página

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#104]
No consigo almacenar una lista múltiple ubicada en una página (no en un popup). Tampoco puedo hacerlo sobreescribiendo el controlador, porque el objeto "solicitud" que se le pasa al mismo no contiene los elementos seleccionados en la página (el campo que se debería cumplimentar está vacío).

   De las entidades que copio abajo, en la página se muestra un combo para "solicitud.baremacion.areasEvaluacion". Este campo viene vacío en el parámetro de entrada del controlador.

Entidad Solicitud extends SolicitudGenerica {
    BasicInfo basicInfo
    SolicitanteExtraInfo solicitanteExtraInfo
    OneToOne Baremacion baremacion
}

Entidad Baremacion {
    OneToOne Solicitud solicitud noCascade noConstruct
    Boolean iniciada
    OneToMany Evaluacion evaluaciones
    ManyToMany AreaEvaluacion areasEvaluacion noCascade
}

**Comment by jelcaf** [comment]
Resuelta en la versión 1.2. Exceptuando que no se especifique en el combo un comboTexto, la cual está resuelta en #108 para la siguiente versión (probablemente 1.3).
