### ISSUE TITLE
Separar SecureController

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#106]
El controlador SecureController tiene dos funcionalidades distintas:
- Mostrar la página de login
- Llevar el control de que el usuario esté logueado

El problema está en que para mostrar la página de login le hace falta extender (@With) de otros controladores `PropertiesFAP` y `MessagesController`. Por lo tanto cada vez que quieras añadir la funcionalidad de controlar que el usuario está logueado te está obligando a que tu controlador también extienda de estos dos.

Lo ideal sería dividir esas dos funcionalidades en dos controladores distintos

**Comment by danieltf** [comment]
Está resuelto en el branch de paginas con identificadores.

Ahora los controladores de paginas y popups que no tienen el atributo "noAutenticar" (casi todos), tienen un @With de CheckAccessController, que se encarga de comprobar si el usuario a logueado o no.

SecureController queda igual que estaba, salvo por la eliminación del método CheckAccess.

Además, ahora todos los controladores de paginas y popups, junto con SecureController, extienden de GenericController, que a su vez tiene varios @With necesarios.
