### ISSUE TITLE
Evaluar utilizar less + twitter bootstrap

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#11]
Evaluar si merece la pena utilizar less + twitter bootstrap.
- Less nos facilitaría la vida a la hora de escribir CSS.
- Con twitter bootstrap los **formularios** quedaría mejor maquetados que lo que tenemos actualmente.

**Comment by axelhzf** [comment]
- Formularios
- Alerts y mensajes de bloque
- Inline labels
- Grids
- Popups (¿Modificar estilo de jQuery UI?)
- Tooltips para la ayuda?
- Breadcrumbs
- Botones
- Topbar no fixed
  - Dropdown para rol de usuario

**Comment by axelhzf** [comment]
Creado branch bootstrap

**Comment by jelcaf** [comment]
Se creó una nueva rama, y se mezcló con la master.
