### ISSUE TITLE
Generalizar la firma

### ISSUE THREAD

**Issue by jelcaf** [FAP-Team/Fap-Module#110]
Generalizar la firma de documentos en el generador. Incluyendo algo como lo siguiente, que genere todo el código necesario para la firma.

```
firma documento=Solicitud.documentoAFirmar simple ...... 
```

**Comment by axelhzf** [comment]
Cambio de estado al tener una firma completa.

Cuando hayan firmado todos los firmantes necesario de una firma indicar que campo se modifica y que valor tiene.
