### ISSUE TITLE
Warnings no son detectados por "hasMessages"

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#112]
Parece que la función "Message.hasMessages()" no considera los mensajes como "warning".

**Comment by pacomf** [comment]
¿En que caso estas probando?

  Yo acabo de probar haciendo un simple:

```
     - Messages.warning("Lo que sea");
     - System.out.println(Messages.hasMessages());
```

  Y si que los considera, me muestra 'true'.

¿Estas haciendo el Message.keep(), para que te lo mantenga de una petición a la siguiente?, no se si podrá ser eso ...

**Comment by ijlopez** [comment]
touché. No había añadido la llamada "Message.keep()".

Gracias.
