### ISSUE TITLE
Falta "import java.util.ArrayList"

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#114]
En la versión 1.2 de FAP, en la función "ValidateCopy" se hace referencia a la entidad "java.util.ArrayList", la cual no es incluída en las cláusulas "import" de la clase, generando así código que no compila.

(En caso de sea un error de FAP, me gustaría que me indicasen si es posible cambiar algo para solucionarlo temporalmente)

Entidad Evaluador extends Agente {
    OneToMany Evaluacion evaluaciones
    ManyToMany AreaEvaluacion areasEvaluacion noCascade
}

Popup PopupEvaluador campo=Evaluador modificar crear borrar titulo="Evaluador" {
    Texto campo=Evaluador.username titulo="Username" requerido
    Combo campo=Evaluador.roles titulo="Roles" busqueda requerido
    Texto campo=Evaluador.email titulo="Email" requerido
    Check campo=Evaluador.funcionario titulo="Funcionario habilitado"
    Combo campo=Evaluador.areasEvaluacion titulo="Áreas evaluación" comboTexto=nombre comboValor=id
}

```
        protected static void PopupEvaluadorValidateCopy(Evaluador dbEvaluador, Evaluador evaluador){
            CustomValidation.clearValidadas();
            CustomValidation.valid("evaluador", evaluador);
```

CustomValidation.required("evaluador.username", evaluador.username);
dbEvaluador.username = evaluador.username;
CustomValidation.validListOfValuesFromTable("evaluador.roles", evaluador.roles);
CustomValidation.required("evaluador.roles", evaluador.roles);
            dbEvaluador.roles.retainAll(evaluador.roles);
            dbEvaluador.roles.addAll(evaluador.roles);
            CustomValidation.required("evaluador.email", evaluador.email);
dbEvaluador.email = evaluador.email;
dbEvaluador.funcionario = evaluador.funcionario;
CustomValidation.validValueFromTable("evaluador.areasEvaluacion", evaluador.areasEvaluacion);
           ArrayList<AreaEvaluacion> evaluador_areasEvaluacionaCT = new ArrayList<AreaEvaluacion>();
           String[] evaluador_areasEvaluacion = params.getAll("evaluador_areasEvaluacion");
           if (evaluador_areasEvaluacion != null) {
                for (String idString : evaluador_areasEvaluacion) {
                    AreaEvaluacion ctr = AreaEvaluacion.findById(Long.parseLong(idString.trim()));
                    evaluador_areasEvaluacionaCT.add(ctr);
                }
           }
           dbEvaluador.areasEvaluacion.clear();
           dbEvaluador.areasEvaluacion.addAll(evaluador_areasEvaluacionaCT);
            }

**Comment by pacomf** [comment]
Efectivamente, al generar el código teníamos un problemilla al no cargar la libreria de ArrayList en los PopUp generados. Esto ya esta solucionado, pero hasta que no salga la nueva versión no se podrá tener operativo. Lo único que puedes hacer es importar tu la librería esa, a mano. Es algo tedioso, pero de momento es la única solución.

Disculpa por los problemillas ocasionados.

**Comment by ijlopez** [comment]
Me gustaría solucionar el problema. Si me pasan la librería y unas pequeñas instrucciones, se los agradecería.

   Saludos.

**Comment by jelcaf** [comment]
Solucionado en la versión 1.2.1, junto con algunos bugs más.
