### ISSUE TITLE
Crear un repositorio git en fap-devel

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#115]
Repositorio en fap-devel para nuestras aplicaciones y pasar de subversion

**Comment by axelhzf** [comment]
Mejor ponerlo en el ubuntu

**Comment by pacomf** [comment]
Esta todo configurado en el Ubuntu (/opt/git-repository/), y tambien se configuro una interfaz gráfica al estilo GitHub, puesta operativa en la dirección: http://fap-devel.etsii.ull.es/git.

Faltaría:
- Que los usuarios pusieran su clave pública en el Ubuntu para acceder a él (Jorge y Paco ya lo tienen hecho, guiarse como lo hicieron ellos)
- Añadir usuarios a la interfaz web (Paco ya ha añadido el de él y el de un Administrador, guiarse como lo hizo él)
- Migrar los proyectos de SVN a este GIT.
- Modificar cualquier otra cosa que vean conveniente (dirección de acceso a la interfaz web, estructura repositorio, etc.)

**Comment by pacomf** [comment]
Migrar los proyectos SVN a este GIT
- Migrados:
  - Innovacion (/opt/git-repository/innovacion)
  - Marco Compensatorio (/opt/git-repository/marcoCompensatorio)
  - Ws-lib (/opt/git-repository/ws-lib)
  - Home Page (/opt/git-repository/homepage)

_NOTA:_ Pasos para migrar un proyecto SVN a nuestro repositorio privado GIT:
http://fap-devel.etsii.ull.es/wiki/index.php/Informaci%C3%B3n#Migraci.C3.B3n_proyectos_SVN_a_GIT
