### ISSUE TITLE
Combo: relación ManyToOne

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#116]
En un combo definido a partir de una relación ManyToOne (y no sé si de otras) no se pasa valor seleccionado en el mismo al controlador del Popup.

Por el momento, la solución pasa por no asociar ningún nombre al elemento "combo" en la definición de la vista. (Daniel Pérez)

Por ejemplo, el error sucede en el popup definido a continuación:

Entidad Evaluacion {
    ManyToOne Baremacion baremacion noCascade
    ManyToOne Evaluador evaluador   noCascade 
    OneToMany Criterio criterios
    OneToMany ConceptoEconomico ceconomicos
    Lista LstEstadoEvaluacion estado
    LongText comentariosAdministracion
    LongText comentariosSolicitante
    OneToMany Historico historico
    ManyToOne TipoEvaluacion tipo noCascade
}

```
Popup PopupAsignacionModificar campo=Evaluacion modificar titulo="Asignar evaluación" {
    Grupo visible=false permiso=noEditable {
        Combo campo=Evaluacion.id titulo="id"
        Combo campo=Evaluacion.baremacion.solicitud.expedienteAed.idAed titulo="Expediente"
        Combo campo=Evaluacion.estado titulo="Estado evaluación"           
    }
    Combo evaluadoresCombo campo=Evaluacion.evaluador titulo="Evaluador" comboTexto=username comboValor=id
}
```

**Comment by pacomf** [comment]
Existe un error con los combos, cuando estos tienen un Nombre y Campo asociados, es decir:

`Combo _NombreCombo_  campo=_NombreCampo_  titulo="Title" comboTexto=name comboValor=id`

El problema es que al GUARDAR, lo que recibe el controlador de ese combo (el id) es el atributo _NombreCombo_, en vez del atributo _NombreCampo_, por lo que no guarda nada.

La solución sería modificar la plantilla HTML del combo, para que en el _id_ que genera lo haga justo al revés, es decir:

AHORA (MAL)

`def id = _id ?: field.id`

LO CORRECTO (BIEN)

`bc. def id = field.id ?: _id`  

---

**ACTUALIZADO**:

El problema se soluciona de otra forma, para que no fallen tambien los MostrarSiCombo, En la plantilla HTML de combo, habría que retocar la manera que se le asigna el 'name' que se utiliza para crear el combo.

ANTES (MAL):

`bc. if (manyTo) name =  id ;`  

AHORA (BIEN)

`bc. if (manyTo)  name = field.id ?: _id ;`  

Se debe dejar como estaba antes la creación de los IDs, en dicha plantilla, o sea:

`def id = _id ?: field.id`

**Comment by jelcaf** [comment]
Al hacer eso, el mostrarSiCombo falla.
