### ISSUE TITLE
Nombre de los parámetros de la función que selecciona las filas de una tabla

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#128]
El nombre del primer parámetro de la función que selecciona las filas de una tabla, en ocasiones, no es el más apropiado. Creo que éste siempre adopta un nombre relacionado con la entidad asociada a la tabla. Por ejemplo: "idEvaluacion", "idDocumento",...

   La confusión se produce cuando en el atributo "campo" de la tabla se especifica un listado de Entidades asociadas a la solicitud. En este caso el identificador que se pasa es el de la solicitud, y el nombre del parámetro sigue estando relacionado con la Entidad; sigue siendo del estilo "idEvaluacion", "idDocumento". En estos casos sería más ilustrativo cambiar el nombre a "idSolicitud" (confunde si no conoces el comportamiento).

   Quizá ya esté solucionado. Daniel me comentó que este listado iba a cambiar.

**Comment by axelhzf** [comment]
No es así como se comporta.

En la aplicación de test puedes ver el ejemplo:

``` javascript
Tabla tablaNombres campo=Solicitud.tablaDeNombres ....
```

Esto genera en el controlador el método

``` java
public static void tablatablaNombres(Long idSolicitud, Long idEntidad)
```

El nombre del primer parámetro se corresponde al id de la entidad desde la que se puede acceder hasta la lista.

¿Puedes poner un ejemplo del comportamiento que dices?

**Comment by ijlopez** [comment]
Upps. Tienes razón. Solo me fijé en el código que no es autogenerado. Siento las molestias.

**Comment by ijlopez** [comment]
No existe el error.
