### ISSUE TITLE
Añadir comando para generar el módulo, desde le propio módulo

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#15]
Ahora mismo hace falta estar en una aplicación para hacer el fap:model

La idea es que desde el propio módulo se pueda generar.
Añadir también al script compiler.xml la llamada para que genere el módulo.

**Comment by jelcaf** [comment]
La generación del módulo ahora se hace únicamente desde el fichero python "generate.py" que se encuentra en el módulo. En el script compiler.xml se añade ahora una llamada a este fichero (con python). Se elimina también el comando fap:module de las aplicaciones fap (se commenta).
