### ISSUE TITLE
Petición: Ampliar el método renderResponse para especificar el nombre del PDF

### ISSUE THREAD

**Issue by mjarysz** [FAP-Team/Fap-Module#152]
A la hora de crear un Informe en PDF facilitaría bastante poder pasar como argumento el nombre del fichero directamente, junto con el resto de argumentos. Por ejemplo:

new Report("reports/plantilla.html").renderResponse( FileName,  args );

**Comment by pacomf** [comment]
Colocado como un método más de la clase Report.

Forma de usarla:
- new Report("reports/plantilla.html").fileName("Nombre").renderResponse(args);

**Comment by axelhzf** [comment]
Utilizar el filename también como prefijo en el renderTmpFile
