### ISSUE TITLE
Configurar Guice para la creación de los servicios bajo demanda

### ISSUE THREAD

**Issue by danieltf** [FAP-Team/Fap-Module#154]
Actualmente, cada vez que Play hace un recargado de las clases, Guice crea todos los servicios configurados, con lo cual el proceso de recargado de clases ahora es mucho mas lento, e incluso puede llegar a dar problemas de permGen Space.

Para solucionar esto hay que intentar configurar Guice para que los servicios se inicialicen solo cuando se vayan a utilizar.

**Comment by axelhzf** [comment]
Problema de concurrencia si dos métodos intentan inicializar los servicios a la vez

**Comment by axelhzf** [comment]
Resuelta en ae19e03 (me equivoqué en el mensaje de log)
