### ISSUE TITLE
Elemento HTML de tipo Fecha

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#197]
En los elementos HTML de tipo Fecha, cuando se inserta un valor se muestra el mensaje "valor incorrecto". Me parece que el error se produce en los controles de validación HTML.

Lo he probado en Firefox y Chrome. He probado varios formatos y no he conseguido que acepte ninguna fecha.

**Comment by jelcaf** [comment]
Mira a ver si el application.conf de la aplicación tiene:

date.format=dd/MM/yyyy

**Comment by ijlopez** [comment]
El problema estaba en la definición de esta propiedad, en la que, por defecto, se usan "guiones" en vez de las barras que usa el control "datepicker".

El DatePicker no funciona conforme a la configuración de la aplicación (mejora propuesta en #198).
