### ISSUE TITLE
Combo: elemento seleccionado en modo lectura

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#200]
Tenemos un combo que mostramos en modo "noEditable", en el cual no se muestra el valor seleccionado en el mismo (según la base de datos). En vez de ello, aparece seleccionado el elemento vacío.

La fuente de datos del combo es una lista FAP.

**Comment by jelcaf** [comment]
No reproducible. Probado con la versión 1.2.2 con los siguientes combos:

``` java
Grupo titulo="Campos sin sobreescribir los controladores manuales" permiso=noEditable {
    Combo campo=Solicitud.comboTest.list titulo="Combo de Tabla de Tablas"
    Combo campo=Solicitud.comboTest.listMultiple titulo="Combo Múltiple de Tabla de Tablas"
    Combo campo=Solicitud.comboTest.ref comboTexto=nombre titulo="Combo de Referencias"
    Combo campo=Solicitud.comboTest.refMultiple comboTexto=nombre titulo="Combo de Referencias Múltiples"
}
```

Y el permiso probado es el "noEditable" del módulo FAP.
Funciona correctamente, con todos los tipos de listas.

**Comment by ijlopez** [comment]
De acuerdo. El problema se debía a que, para asignar el valor de la lista, uso el valor de "crearEnumerado". Yo creía que éste asignaba la clave del par, y no el título. Por lo menos así es como lo planteé cuando les propuse autogenerar "enumerados" paralas listas. ¿No creen que es más útil?

En principio, yo estoy interesado en usar los enumerados de la siguiente forma:

datosAsunto.estadoAsunto = EstadosAsuntoEnum.INICIADO.toString();

Es decir; no tener que escribir las claves en el código.

**Comment by jelcaf** [comment]
Ahora mismo para acceder al valor de la clave, existe el método name(): EstadosAsuntoEnum.INICIADO.name().

En las siguientes versiones de fap (a partir de la 2.0), los enumerados tendrán 3 métodos:
name() -> clave
value() -> valor
toString() -> [clave]valor

**Comment by ijlopez** [comment]
De acuerdo. Estaba usando el método "toString()" para acceder a la clave.
