### ISSUE TITLE
Elemento Persona: campo 'email'

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#208]
El DSL de las nuevas aplicaciones requieren a las personas el campo 'email'. Para ello, necesitaríamos que el elemento PersonaFisica incluyese el campo 'email'.

Hemos probado a extender la entidad PersonaFisica pero luego, al añadir el campo en el DSL que lo representa gráficamente, el cuadro de texto del email queda bastante mal; queda por fuera del marco que delimita los controloes del elemento PersonaFisica.

**Comment by jelcaf** [comment]
Permitiremos que los elementos Solicitante, Persona, PersonaFisica, PersonaJuridica, ... no incluyan el cuadro que los agrupa (atributo "noTitulo" o algo así). De esta manera, podremos incluir un grupo con este elemento y todos los elementos que queramos.
