### ISSUE TITLE
Permisos.fap 1.2.2 EOF error al principio del archivo

### ISSUE THREAD

**Issue by isabbagh** [FAP-Team/Fap-Module#209]
Hola,

He instalado la versión 1.2.2, he creado un nuevo proyecto desde cero, pero al meter mi código (mis archivos .fap del led), en  el archivo Permisos.fap de fap-1.2.2, eclipse me da constantemente "missing EOF at 'rule'" al principio de ese archivo, y por ende a todos los permisos de mi código.  ¿Alguna pista de por qué puede estar pasando esto?

**Comment by jelcaf** [comment]
Hola, el plugin para el editor de eclipse de la versión 1.2.2 no está del todo bien. La generación y demás, funciona correctamente. En los próximos días sacaremos la versión 1.2.3 con el plugin correctamente.

**Comment by isabbagh** [comment]
ok..
