### ISSUE TITLE
version 1.2.2, Agrupar y alineación de sus elementos agrupados

### ISSUE THREAD

**Issue by isabbagh** [FAP-Team/Fap-Module#210]
Cuando agrupas una caja de texto y un botón, el botón se alinea a la altura del título del texto, no de la "caja" en sí , por lo que gráficamente no queda muy bien

**Comment by axelhzf** [comment]
Puedes poner el código que estas utilizando y una captura de pantalla?

**Comment by isabbagh** [comment]
El código en http://pastebin.com/EqUFG3Sy, la captura de pantalla en http://picturepush.com/+W3r6

**Comment by isabbagh** [comment]
Haciendo que la etiqueta del texto quede siempre a la altura de la caja de texto, se minimiza este problema, (ampliando el ancho del control)
