### ISSUE TITLE
LOGOS: Cabecera del titulo de la aplicación (página principal)

### ISSUE THREAD

**Issue by txutxi** [FAP-Team/Fap-Module#221]
Es una sugerencia:

Sería conveniente que reservar el ancho de la cabecera de la aplicación para poner una unica imagen. Que ocupe toda la cabecera.
Siempre es más fácil colocar siempre una y solo una imagen, que no tener que modificar la plantilla de la aplicacion para colocar un logo, dos, o cuatro dependiendo de la aplicación.

**Comment by jelcaf** [comment]
Se creará un fichero cabecera.html (o header.html) y es el que podrán sobreescribir fácilmente, colocando las imágenes que se quieran. Para que la actualización a la versión 2.0 de fap, con redimensionado de páginas no afecte a las aplicaciones actuales.
