### ISSUE TITLE
boton: información al hacer clic sobre el mismo

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#224]
Tenemos una página que al final de l formulario incluye dos botones:

```
Pagina  CrearSolInforme titulo="Crear solicitud de informe" noForm {

   ...
   ...
   ...

   Form botones {
      AgruparCampos {
         Boton solicitarInforme titulo="Solicitar informe"
         Boton guardar titulo="Guardar" 
      }
   }
}
```

Como resultado, se crea el método "botones":

```
public static void botones(Long idSolicitud, String solicitarInforme, String guardar) {
 ...
 ...
}
```

El caso es que siempre se invoca al método "botones" con los parámetros de los botones con valor NULL; como si no se hubiese pulsado ningún botón. No sé si hemos cometido un fallo en el DSL. ¿A qué se debe?

**Comment by jelcaf** [comment]
Está solucionado para las versiones 1.2.4 en adelante (suponemos que saldrá hoy o mañana). Solución mientras poner un solo botón en cada form.
