### ISSUE TITLE
Métodos privados de los proxies para el acceso a los Servicios Web

### ISSUE THREAD

**Issue by ijlopez** [FAP-Team/Fap-Module#229]
Tengo que añadir llamadas a funciones que no se encuentran registradas en los proxies "AedClient" y "TiposDocumentosClient". Para ello tengo problemas porque las variables claves de ambas clases están declaradas como "private", así como algunos métodos importantes. ¿Existe alguna razón importante para ello? Es que si no fuera así, para facilitar la extensión de los proxies, estaría bien que las declararan, al menos, como "protected".

En concreto, las variables y métodos a los que he tenido que cambiar el modificador de ámbito son:

AedClient:
- Variable "aed"
- Variable "log"

TiposDocumentosClient
- Variable "tipos"
- Variable "procedimientos"
- Variable "log"
- Métodos "aedError"

**Comment by jelcaf** [comment]
En principio si se podrían poner como "protected". Lo tendremos en cuenta para la siguiente versión.
