### ISSUE TITLE
Fallo en upload.html al poner en producción

### ISSUE THREAD

**Issue by jlucasgl** [FAP-Team/Fap-Module#243]
Hemos detectado un error en views.tags.fap/upload.html al poner en producción nuestra aplicación y tratar de acceder a una página en la que existe un campo Subir. El error en concreto es un puntero null que da la siguiente linea de upload.html :

<div class="control-group ${play.mvc.Controller.validation.current().hasError(id)? "error" : ""}">

Actualmente hemos detectado el fallo con la versión nb300312. 

Al parecer cuando llega a este punto, play.mvc.Controller.validation es null.
Temporalmente hemos solucionado este asunto sobreescribiendo la vista en app/ y retirando el valor de class.
Esto solo afecta a que ahora no se resalta, en rojo como requerido, cuando no se selecciona un fichero para subir

Este mismo código sigue presente en la versión nb180412 . Se ha solucionado esto ya ?

**Comment by pacomf** [comment]
Buenas, 

   Ya esta solucionado. A partir de la NB de hoy el problema no se reproducirá más. No obstante, si quieres continuar con la version de la NB que tienes, simplemente debes cambiar la línea que comentabas que fallaba en el 'upload.html' por:

`<div class="control-group ${((play.mvc.Controller.validation!=null) && (play.mvc.Controller.validation.current().hasError(id))) ? "error" : ""}">`

Como puedes ver en :

https://github.com/FAP-Team/Fap-Module/commit/be1e36f7e28dbb3efb2c1917c05ccf876e91bce4#diff-3

Saludos.

**Comment by pacomf** [comment]
`play.mvc.Controller.validation`

No funciona en modo Producción.
