### ISSUE TITLE
Personalizar la primera pantalla de FAP

### ISSUE THREAD

**Issue by pacomf** [FAP-Team/Fap-Module#252]
Personalizar la primera pantalla de FAP, de modo que para el rol Usuario se muestre como hasta ahora (un listado con los expedientes), y para el resto de roles (Administrador, gestor, revisor), aparezca una pantalla de búsqueda para evitar que cuando existan muchos expedientes, tarde en carga la tabla que existe hasta ahora, y de esa manera filtrar los resultados que apareceran en dicha tabla.

**Comment by jelcaf** [comment]
Una property que indique si se quiere este comportamiento. Por defecto no se quiere ese comportamiento.

fap.index.search=true (o algo parecido)
