### ISSUE TITLE
Página De Presentación en el módulo

### ISSUE THREAD

**Issue by jelcaf** [FAP-Team/Fap-Module#277]
Incluir la página de Presentación en el módulo FAP: **PaginaPresentacionFAP**.

Además incluirá:
- Preparar para firmar
  - Comprobará la obligatoriedad de documentos.
  - Creará los documentos (borrador y oficial)
- Modificar
- Firmar y Registrar
- ....

**Comment by pacomf** [comment]
Commit 774edb9 con documentación en commit 1271628
