### ISSUE TITLE
Evaluar el uso de Bootstrap-DatePicker

### ISSUE THREAD

**Issue by jelcaf** [FAP-Team/Fap-Module#286]
https://github.com/eternicode/bootstrap-datepicker/

Evaluar si vale la pena incluir Bootstrap-Datepicker:
- Tamaño
- Aspecto
- Ventajas
- ...

**Comment by mjarysz** [comment]
Integrado Bootstrap-DatePicker utilizando el ejemplo de https://github.com/Aymkdn/Datepicker-for-Bootstrap. Está probado en IE7, IE8, IE9, Firefox y Chrome.
