### ISSUE TITLE
Separar los tipos de documentos Aceptación y Renuncia

### ISSUE THREAD

**Issue by jelcaf** [FAP-Team/Fap-Module#299]
Crear 2 properties:

**fap.aed.tiposdocumentos.aceptacion**
**fap.aed.tiposdocumentos.renuncia**

Y en la clase _TramiteAceptacionRenuncia_, hacer depender los métodos necesarios de el valor de _solicitud.aceptarRenunciar.seleccion_.

**Comment by pacomf** [comment]
Las properties ahora son:

_fap.aed.procedimientos.tramiteaceptacionrenuncia.aceptacion.nombre_
_fap.aed.procedimientos.tramiteaceptacionrenuncia.renuncia.nombre_
_fap.aed.tiposdocumentos.aceptacionrenuncia.aceptacion_
_fap.aed.tiposdocumentos.aceptacionrenuncia.renuncia_
_fap.aed.tiposdocumentos.justificanteRegistroAceptacionRenuncia.aceptacion_
_fap.aed.tiposdocumentos.justificanteRegistroAceptacionRenuncia.renuncia_

**Comment by pacomf** [comment]
Commit: aeb3698
