### ISSUE TITLE
Facturas Electrónicas

### ISSUE THREAD

**Issue by jelcaf** [FAP-Team/Fap-Module#320]
Recoletar información y realizar pruebas simples para facturas electrónicas.

**Comment by mjarysz** [comment]
https://github.com/FAP-Team/Fap-Module/commit/b47a462946fdcb189147ad89f1f681310f0d30c3

**Comment by mjarysz** [comment]
https://github.com/FAP-Team/Fap-Module/commit/baa1dc44f432673d1106b59ecbc2c06b36b26f26
