### ISSUE TITLE
"ClassFormatException: null"

### ISSUE THREAD

**Issue by alejandroaadm** [FAP-Team/Fap-Module#350]
Hola.
Acabo de empezar a trabajar con FAP, he seguido todos los pasos de la página ofical instalando:
- Java JDK v8
- Apache-ant v1.9.3
- Typesafe activator v1.0.13
- Play Framework v1.2.4
- Fap v2.0

He creado el proyecto, modificado el fichero de dependencias a: 
require:
    - play
    - fap -> fap 2.0
    - fap-modules -> guice 1.3
    - play -> pdf 0.6
    - play -> less 0.3
    - play -> recaptcha 1.2
    - play -> mockito 0.1
    - play -> webdrive 0.2:
        transitive: false
repositories:
    - Fap repository:
        type: http
        artifact: "http://fap-devel.etsii.ull.es/public/fap-sdk2/[revision]/[module]-[revision].zip"
        contains:
            - fap -> fap
    - fap-devel modules repository:
        type: http
        artifact: "http://fap-devel.etsii.ull.es/public/repo/[module]/[revision]/[module]-[revision].zip"
        contains:
            - fap-modules -> guice

He generado las dependencias mencionadas, generado el proyecto y arrancado, pero al meterme en "localhost:9000" me salta un error de:

Oops: ClassFormatException

An unexpected error occured caused by exception ClassFormatException:
null
This exception has been logged with id 6hl04jcaa

He buscado por todos lados pero este error en concreto no consigo encontrarlo, ¿podrían ayudarme?

Gracias de antemano

**Comment by eleazarhdez** [comment]
Buenos días, para dudas con la instalación del módulo y problemas al ejecutar envíanos un e-mail a la siguiente dirección: 

fap-support@googlegroups.com

Te atenderemos lo más rápido posible.
