### ISSUE TITLE
Notificaciones con id null

### ISSUE THREAD

**Issue by eleazarhdez** [FAP-Team/Fap-Module#351]
No se pueden realizar las notificaciones porque el id de las mismas es nulo por alguna causa.

{"time":"2014-03-28 07:46:41,356","level":"ERROR","class_":"play","user":"XXXXXXX","message":"El gestor XXXXXXX no pudo realizar la operación de puesta a dispoción para la notificación null al obtenerse un error desconocido. Could not send Message.","trace":""}
{"time":"2014-03-28 07:46:41,450","level":"ERROR","class_":"play","user":"XXXXXXX","message":"No se ha podido enviar la notificación 334: Error desconocido. Could not send Message.","trace":""}

**Comment by alecabdia** [comment]
Fixed in 4a9744d36cec9d3c4e2ceaed77dc6215179b8f51 and e74d6ac13afcc51d11b8ae06f81b01f1199c5ad3
