### ISSUE TITLE
Eliminar cuadro diálogo al firmar con @firma

### ISSUE THREAD

**Issue by eleazarhdez** [FAP-Team/Fap-Module#352]
Al usar la firma múltiple con el cliente @firma siempre sale un cuadro de diálogo que hay que aceptar. Se trata de intentar evitar que salga ese cuadro de diálogo para que el gestor pueda realizar la firma múltiple haciendo un solo click.

![](http://puu.sh/7MBqG/37fee81935.png)

**Comment by fergz** [comment]
Cerrado con 275c0d0b4b6fa1fb3b7468a23dfca7a2fbdbe059 y 0f9dd66a8b90e4c4f0daa1aabe6e0e51eb5c55a2 utilizando la firma masiva del cliente @firma

El mensaje de permiso es dependiende del cliente @firma y aparece por cada documento a firmar. El cliente ofrece también la funcionalidad de firma masiva, pidiendo permiso tan solo al inicio de la operación de firmado, pudiendo realizar la firma masiva de varios documentos. 
En cualquier caso siempre pedirá al menos una vez el mensaje de permiso.
