### ISSUE TITLE
Comprobar funcionamiento de nuevas librerías

### ISSUE THREAD

**Issue by eleazarhdez** [FAP-Team/Fap-Module#361]
Probar las nuevas librerías de libro de resolución y libro de certificados (v20140512) y comprobar que el funcionamiento es el adecuado.

**Comment by lagunero** [comment]
Comprobado el funcionamiento de la nueva versión de las librerías de libro de resolución y certificados. El funcionamiento de dichas librarías se corresponde con lo esperado, la inyección y llamada a métodos funcionan correctamente devolviendo los datos esperados desde los servicios.
