### ISSUE TITLE
Mejorar Usabilidad en Resolución

### ISSUE THREAD

**Issue by eleazarhdez** [FAP-Team/Fap-Module#368]
1.- En la página de resoluciones modificar los títulos de las columnas.
    a) Cambiar campo "Resolución" por "Título", en el cual se mostrará el título de la resolución.
     b) Cambiar campo "Modalidad" por "fecha"

![issue1](https://cloud.githubusercontent.com/assets/1478997/3051466/1d25e79a-e18d-11e3-96ed-6341acccce98.png)

2.- Cuando seleccionamos un elemento en la tabla y nos movemos con el scroll, al soltar el mismo y mover la posición del ratón, la tabla vuelve a colocarse en el último elemento seleccionado. Arreglar este comportamiento (JS- Sencha)
![issue2](https://cloud.githubusercontent.com/assets/1478997/3051500/bb89f5a2-e18d-11e3-983d-d20de847f544.png)

En esa misma página habrá que coger el "comportamiento y las acciones" del botón "Seleccionar" de la tabla y añadírselo a un botón nuevo que habrá que crear justo a continuación de la misma.

Además se deberá añadir un panel o elemento en el que se muestren en "tiempo real" las elecciones que va haciendo el usuario en cada momento.

3) Por último en la página que se muestra a continuación,
![issue3](https://cloud.githubusercontent.com/assets/1478997/3051545/6baf9446-e18e-11e3-8ae1-33b6b1745729.png)

 deberemos mostrar un botón "Atrás" en el que podamos volver a todo lo anterior. Hay que tener en cuenta que el estado de la resolución se encuentra en "Creada", y hay que volverlo a pasar a "Borrador" con todo lo que ello implique.

**Comment by lagunero** [comment]
Se resuelve la incidencia mediante las modificaciones realizadas en los siguientes commits:
- 98f75563e51b08f8b2b370f2f654f6480a7ac355: Modificada la tabla de resoluciones para mostrar el titulo de la resolucion y la fecha.
- c658831b5562a92fdd30204675b4527967ec50e7: Se modifica la tabla de expedientes para resolver el comportamiento erróneo al desplazarse por la misma y para mostrar un mensaje cuando se selecciona un expediente.
- fe5cd73fe98f6044553b3e8fe0562066c5e9f8fb: Se añade un botón volver a la página preparar resolución que devuelve a la página de selección de expedientes.

**Comment by eleazarhdez** [comment]
Cuando se realiza una selección en la tabla no debe aparecer un alert. Debe ir apareciendo en tiempo real las opciones elegidas por el usuario.
