### ISSUE TITLE
Cambio de hosts en  getFirmaEnClienteJS

### ISSUE THREAD

**Issue by eleazarhdez** [FAP-Team/Fap-Module#374]
En el fichero PlatinoFirmaServiceImpl.java en el método getFirmaEnClienteJS(), debemos contemplar que dependiendo de la url base que tengamos el prefijo del host será uno u otro.

Ejemplo:

Si url base = www.gobiernodecanarias.org entonces
 host = host = "https://www.gobiernodecanarias.org/platino/servicios/sfst/js/";
Si url base = sede.gobcan.es entonces
 host = host = "https://sede.gobcan.es/platino/servicios/sfst/js/";

**Comment by fergz** [comment]
Pendiente de hacer la mezcla a rama de arrobaFirmaMiniapplet
