### ISSUE TITLE
Error estados Verificación

### ISSUE THREAD

**Issue by eleazarhdez** [FAP-Team/Fap-Module#378]
La semana pasada los gestores de tesis realizaron la verificación de un trámite, el de justificación de gastos, en el expediente de oficio de la ULL.
El hecho es que todo el proceso fue bien, incluso se envió la notificación del requerimiento, pero  una vez enviada el proceso en la aplicación no continuó y dio un null pointer, los estados de la verificación, de la notificación y la situación de los documentos (verificados o no) hubo que arreglarlo manualmente en la base de datos. Por lo que deduzco de los mensajes de los logs y otros que he puesto en el código en las pruebas en local el error está al guardar la notificación alrededor de la línea 340 de NotificacionServiceImpl.java, te envío la información de los logs a ver si encuentran donde está el problema.

![issue5](https://cloud.githubusercontent.com/assets/1478997/3254554/8fbff7be-f1fa-11e3-85a3-b1e42339de12.png)

No he detectado que se produzca un error cuando lanzamos la notificación de una resolución
Seguiré haciendo pruebas con la verificación de un trámite solicitud para comprobar si ocurre con la verificación de todos los trámites o sólo con este.

![issue6](https://cloud.githubusercontent.com/assets/1478997/3254556/96dcc860-f1fa-11e3-988a-a864d692e0ad.png)
![issue7](https://cloud.githubusercontent.com/assets/1478997/3254557/99b33eb6-f1fa-11e3-8899-cfe886451d73.png)
![issue8](https://cloud.githubusercontent.com/assets/1478997/3254559/9ddfb230-f1fa-11e3-9aa6-69d6966c9c2a.png)

**Comment by fergz** [comment]
He realizado varias verificaciones con distintos trámites y no consigo reproducir el error. Haciendo la traza del log y el código parece que fue un error puntual al obtener la información desde el servicio web de notificaciones.
Cierro la issue, pero quedamos atentos a nueva información o que se vuelva a producir
