### ISSUE TITLE
Guardar hash cuando se aporta un documento mediante uri

### ISSUE THREAD

**Issue by alecabdia** [FAP-Team/Fap-Module#383]
Cuando se aporta un documento existente mediante uri éste no tiene el campo hash en la base de datos. Sin embargo, cuando se aporta un documento nuevo sí tiene dicho campo. Se debe guardar el campo hash en los dos casos.

**Comment by fergz** [comment]
Commit válido: 1e2d4eaf85728d1f5ce202238c0360988c7aea5a. El anterior fue un error usando el cliente git
