### ISSUE TITLE
Limpieza de ramas obsoletas

### ISSUE THREAD

**Issue by eleazarhdez** [FAP-Team/Fap-Module#391]
Eliminar todas las ramas que se encuentren obsoletas. Asegurarse de que no son ramas que van a ser utilizadas en el futuro.

**Comment by fergz** [comment]
Eliminadas las ramas ya mezcladas en otras.
Eliminadas las ramas de versiones y sustituidas por tags de git
Pendientes algunas ramas, como las de metadatos, para aprovechar código en un futuro o retomar el trabajo
