### ISSUE TITLE
Combos overlay

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#42]
Arreglar que los combos cuando se despliegan ruedan el resto de elementos en lugar de ponerse encima.
El problema estaba con los popups. Si el combo estaba al final del popup y el combo es grande, debería salirse por fuera del popup.

**Comment by axelhzf** [comment]
El problema es el siguiente

``` html
<popup>
    <div style="position:absolute"/>
<popup>
```

La posición en absoluta con respecto al popup y por lo tanto no puede salirse fuera del popup.

Como está hecho la datepicker, que si funciona correctamente es que el elemento no lo pone en el lugar que se define, sino en el body de la página. Por ejemplo

``` html
<body>
    <popup>
          <campo fecha>
    </popup>
    <codigo para el datepicker>
<body>
```

**Soluciones:**
- Modificar la librería chosen para que permita esto. El código está escrito en cooffescript aunque no parece muy complicado https://github.com/harvesthq/chosen/blob/master/coffee/chosen.jquery.coffee
- Añadir código js para mover el código añadido por la librería desde el popup al body

**Comment by jelcaf** [comment]
Arreglado al utilizar twitter bootstrap.
