### ISSUE TITLE
Desplegar aplicaciones

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#43]
Dani me pidió que es lo que hace falta para desplegar las aplicaciones en fap.
Creo que podríamos decirle de desplegarlas en servidores de play -> Mejor rendimiento y menos problemas. Además funcionarían los jobs (que no funcionan en tomcat)

El principal problema que está detectando es el tema de las rutas (Problema que tuvimos en la página de la documentación).
Suponiendo que despliegas la aplicación en:

http://localhost:9000/

Pero despues desde el apache, quieres redirigirla a

http://localhost:80/aplicacion-wapa-play/

Las rutas que tengas absolutas, como por ejemplo las rutas a los recursos(javascript, css e imagenes) no las encuentra bien.

Por lo tanto, hay que probar a configurar correctamente apache con un reverse proxy.

**Comment by pacomf** [comment]
Esta casi terminado, ahora falta mirar porque al hacer el ProxyReverse, las tildes y demás caracteres especiales no los reconoce el Apache, el fallo esta en alguna configuracion de "ProxyHTMLURLMap" que es la que se encarga de montar las rutas adecuadamente

**Comment by pacomf** [comment]
Solucionado!, el problema era que en las cabeceras de la plantilla HTML de la documentación de la aplicación no estaba puesto : 
"<meta http-equiv="Content-Type" content="text/html; charset=utf-8">", por lo que había el problema de las tildes y caracteres extraños sólo en las páginas de documentación.

**Comment by axelhzf** [comment]
La aproximación de utilizar libxml para arreglar los enlaces, parece que se suele utilizar, pero no me parece muy adecuada. Me parece que no escala demasiado. Si ese tomcat estuviera como frontal de muchas aplicaciones, sería el encargado de hacer el parser de todas las peticiones de todas las aplicaciones.

**Comment by axelhzf** [comment]
Con la property http.path y la redirección adecuada es suficiente
