### ISSUE TITLE
Ruta del botón de subir Archivo

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#5]
Cuando la aplicación se despliega en un Tomcat no se muestra el botón para subir archivo.

Probablemente es por la ruta del fichero, que esté puesta como absoluta, cuando en realidad debería ser relativa.

Cuando se despliega en desarrollo    http://localhost:9000/public/images/boton.png
Cuando se despliega en produccion  http://lcoalhost:8008/marcoCompensatorio/public/images/boton.png

Es preferible que el botón no tenga estilo a que el botón no se muestre. Si vemos que tenemos problemas, quitar el estilo.

**Comment by jelcaf** [comment]
Se cambia la ruta de la imagen del botón a relativa
