### ISSUE TITLE
Poner tag de idioma en la plantilla

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#54]
Para que el google chrome no piense que la página está en gallego xD

**Comment by jelcaf** [comment]
Incluido lang="es" en la plantilla

**Comment by axelhzf** [comment]
Chrome sigue pasando del idioma que le pusimos, parece que eso no es suficiente.
Aquí comentan una posible solución:

http://stackoverflow.com/questions/2467454/why-does-chrome-incorrectly-determine-page-is-in-a-different-language-and-offer

**Comment by jelcaf** [comment]
Se le añadió, tal como se dice en http://www.google.com/support/webmasters/bin/answer.py?hl=es&answer=79812

   <meta name="google" content="notranslate" />
