### ISSUE TITLE
Actualización del cliente del AED

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#55]
Envié un correo a fap-equipo con las instrucciones.
Según pone ahí habrá que actualizar el cliente.

**Comment by jelcaf** [comment]
Es únicamente la librería lo que hay que cambiar.
Nueva versión: eadmon-aed-client-1.1

**Comment by jelcaf** [comment]
Actualizados los pom.xml de las aplicaciones antiguas.
Actualizada también a las aplicaciones nuevas.
