### ISSUE TITLE
Subir archivo debe mostrar distintos tipos de documentos según el trámite

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#58]
Tal como te adelanté por teléfono es necesario que podamos tener diferentes listas a la hora de subir el documento. Las listas de documento que debe aparecer en el combo depende del trámite en el que estemos.

Actualmente, en la BD de Procedimiento. Asociado a un procedimiento podemos tener varios trámites.

El trámite se identifica con una URI

Diferentes trámites pueden tener asociado el mismo tipo de documento.

Ahora solo recogemos los tipos de documentos asociados al tramite solicitud y cargamos 3 listas de documentos en la tabla de tablas: tipoDocumentosTodos, tipoDocumentosCiudadanos, tipoDocumentosOrganismo

Lo que se pretende es tengamos listas del tipo tipoDocumentosCiudadanos  y tipoDocumentosOrganismo por trámite.

Creo que lo mejor es que desde el DSL se defina un lista de los trámites asociados a la convocatoria, en el que se especifique el nombre del trámite y su URI

```
Lista tramites {
      solicitud: "eadmon://gobcan.es/tramitesProcedimientos/TRP000000000000000002"
      aceptacion: "eadmon://gobcan.es/tramitesProcedimientos/TRP000000000000000005"
      reformulacion: "eadmon://gobcan.es/tramitesProcedimientos/TRP000000000000000006"
      alegaciones: "eadmon://gobcan.es/tramitesProcedimientos/TRP000000000000000007"
}
```

El proceso que carga desde el AED cargará por un lado

La tabla tipoDocumentosTodos, será la lista de todos los documentos de todos los trámites, habrá que tener en cuenta los documentos que puedan estar en más de un trámite para sólo cargarlos una vez

Y por cada clave de la tabla tramites cargará dos tabla tipoDocumentosCiudadanos y tipoDocumentosOrganismo

Los nombres de estas tablas que se creen tendrán como parte del nombre la clave de la tabla tramites. Por ejemplo para el tramite solicitud
podrían ser tipoDocumentosCiudadanosSolicitud y tipoDocuemntosOrganismo solicitud

Cuando en el DSL  indicamos

```
                    SubirArchivoAed fileAportacion campo=Documento requerido
```

Debemos especificar qué lista queremos usar como parámetro, si no se especifica ninguna podríamos tener por defecto la lista tipoDocumenosTodos

```
   SubirArchivoAed fileAportacion campo=Documento lista=tipoDocumentosCiudadanosSolicitud requerido
```

En este caso la lista que se usaría sería la de los documentos asociados al trámite solicitud que puede aportar el ciudadano

Esto que planteo es un propuesta, si tienen otra alternativa mejor, decidan ustedes cómo hacerlo.

**Comment by axelhzf** [comment]
Están creadas las páginas en la administración y el tag modificado.

Falta cambiar la gramática

**Comment by jelcaf** [comment]
En principio en la gramática el cambio está con:

```
    & ('tramite' '=' tramite=CampoLista)?       
    & ('aportadoPor' '=' aportadoPor=STRING)?
```

Aunque podrían ser los dos como STRING o los dos como elementos de una lista.

**Comment by jelcaf** [comment]
Finalemente la gramática queda así:

```
& ('tramite' '=' tramite=STRING)?       
& ('aportadoPor' '=' aportadoPor=STRING)?
```
