### ISSUE TITLE
Crear un script para iniciar un proyecto

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#67]
Crear un script bash y .bat para crear un proyecto desde cero.
- Crear el proyecto play
- Añadir dependencias
- Ejecutar fap-init

**Comment by pacomf** [comment]
Ya estaría, está hecho en Python y se le pasa como parametro, en línea de comandos, el 'nombre del proyecto'.

La dirección donde se encuentra el script es:

http://fap-devel.etsii.ull.es/public/fapInitScript/init-script.py

**Comment by pacomf** [comment]
Documentar como utilizar dicho script
