### ISSUE TITLE
Crear enums a partir de las listas

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#70]
Para listas creadas en el DSL creo que actualmente no se genera código en el paquete "models". Un inconveniente de ello es que programando, en ocasiones, me veo obligado a escribir directamente el literal correspondiente al código de la lista. Actualmente, para servirme del "IntelliSense" del IDE, lo que hacemos es declarar un "enum" para las listas más usadas. Por ejemplo, para los tipos de Estados de Evaluación escribo algo como lo siguiente:

``` java
public enum EstadoEvaluacionEnum {

    NO_ASIGNADA("noAsignada"),
    ASIGNADA("asignada"),
    ...
    ...;

    private String valor;

    private TipoEstadoEvaluacion(String valor) {
        this.valor = valor;
    }

    @Override
    public String toString() {
        return this.valor;
    }
}
```

   A lo mejor un código parecido podría ser autogenerado para aquellas listas a las que se añadiera un determinado atributo. De esta manera, además, un cambio en un elemento de la lista haría que el IDE señalase un error de sintaxis, lo cual también estaría bien.

**Comment by pacomf** [comment]
Realizado!, las clases Java de tipo Enum, se almacenan en una nueva carpeta: enumerado/gen/, dentro de /app
