### ISSUE TITLE
Crear una evaluación por solicitud

### ISSUE THREAD

**Issue by smontelongo** [FAP-Team/Fap-Module#71]
Para la aplicación de proyectos de innovación vamos a crear una evaluación por solicitud. Esta evaluación será accesible por los gestores desde el submenú instrucción de la aplicación. Los permisos de acceso deberían ser similares a los del apartado verificación.

No es necesarios que en la evaluación se muestre la lista de documentos.

**Comment by axelhzf** [comment]
En la definición del tipo de evaluación de innovación. Puse el atributo de los comentarios de forma aleatoria.
Todos los criterios deberían llevar comentarios? No debería llevar comentarios ninguno?

**Comment by axelhzf** [comment]
Estoy revisando el cálculo de los criterios automáticos, en concreto el del criterio C (Empleo generado) y hay casos que no están contemplados. Por ejemplo:

Pequeña empresa - 1 contrato

**Comment by smontelongo** [comment]
Se pondrán comentarios uno general para la evaluación y los criterios A,B y C, es decir los de primer nivel, que son los que aparecen en las bases

**Comment by axelhzf** [comment]
¿Te parece correcto que ponga la baremación en una sección aparte, tal como lo tenía hasta ahora, en vez de en un apartado dentro de la solicitud? 
En la ficha del evaluador puede añadir algo de información del expediente y un enlace al expediente. De esta forma no tengo que modificar nada y ya está preparado para el caso más genérico.
