### ISSUE TITLE
Incluir la documentación "html" (documentación-codigo) en el controlador de Documentación

### ISSUE THREAD

**Issue by jelcaf** [FAP-Team/Fap-Module#75]
Incluir en el controlador de la documentación, los ficheros html generados a partir de los ".fap".

**Comment by pacomf** [comment]
Parece que funciona!, falta revisar bien como lo hace en la WEB ...

**Comment by pacomf** [comment]
Probado en la WEB (Hay cambios en el controlador por las rutas, respecto a lo del Modulo y la WEB), pero funciona!
