### ISSUE TITLE
Problemas con el crearEnumerado en las listas

### ISSUE THREAD

**Issue by jelcaf** [FAP-Team/Fap-Module#77]
Aparecen problemas si sobre escribes una lista del módulo fap, añadiéndole nuevos estados. Para arreglarlo, quizás:
1. Deberíamos colocarlos en paquetes diferentes (los del módulo en "enumerados.fap.gen" y los de la aplicación en "enumerados.gen" por ejemplo).
2. En los de la aplicación, añadir los valores que contienen los enumerados del módulo que se sobreescriben.

**Comment by pacomf** [comment]
Parece que ya esta solucionado ...
