### ISSUE TITLE
Crear plantilla PDF baremación

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#81]
Crear la plantilla html de la baremación similar a lo que se muestra en la página, pero que en la parte de arriba tenga un resumen con los valores que tiene cada uno de los criterios y los conceptos económicos

**Comment by pacomf** [comment]
Primera versión del borrador lista ...

**Comment by axelhzf** [comment]
Las correciones del pdf se están poniendo en la incidencia #90
