### ISSUE TITLE
Utilización en el módulo de los permisos de Permission.java

### ISSUE THREAD

**Issue by danieltf** [FAP-Team/Fap-Module#82]
En los controladores del módulo FAP actualmente se están usando los métodos de permisos existentes en la clase PermissionFap.java, que es la que se genera en el proyecto del módulo. El problema que esto tiene es que si en una aplicación que utilice el módulo se define en el DSL un permiso con el mismo nombre (con fines de sobrescribirlo), en los controladores del módulo se seguirá usando el permiso definido originalmente.

Algunas soluciones a este problema:
- cambiar en el módulo para que utilice la clase Permission.java, que se define en cada aplicación. Problema: que al no existir dicha clase en el módulo, existirá un error de compilación en el proyecto.
- Utilizar un sistema de inyección de dependencias sencillo creado por nosotros.
- Utilizar algún sistema de inyección de dependencias, como Spring o Guice.

**Comment by axelhzf** [comment]
Falta documentar la nueva forma de acceder a los permisos y cómo funciona le inyección de dependencias
