### ISSUE TITLE
Añadir "Gran Empresa" en el combo de categoría en las aplicaciones de producción

### ISSUE THREAD

**Issue by smontelongo** [FAP-Team/Fap-Module#83]
Incluir en el apartado de declaraciones en combo de categoría “Gran  Empresa”. 
Sería en las 3 aplicaciones (Tecnólogos, Proyectos de Innovación y Cluster) y también en las migraciones de Proyectos de Innovación y Clúster

**Comment by jelcaf** [comment]
Incluida en todos. Faltaría subirlas a PRO y PRE (las necesarias)
