### ISSUE TITLE
Añadir el total de la evaluación

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#87]
Añadir en algún sitio el total de la evaluación.
No añadirlo como un criterio nuevo, porque sino toda la jerarquía de los criterios debería empezar por ese prefijo.

**Comment by pacomf** [comment]
Añadido como atributo de la entidad Evaluacion, de Baremación.

Para sobrecargar la función que calcula el total de la evaluación, deberemos sobreescribir el método

evalTotalCriterios(Evaluacion E, List <Criterio> L),

desde la aplicación en cuestión.
