### ISSUE TITLE
Revisión Baremación

### ISSUE THREAD

**Issue by jelcaf** [FAP-Team/Fap-Module#90]
Arreglar los fallos reportados en el PDF de Sole.

**Comment by pacomf** [comment]
Esta todo, a excepción de poder quitar los Valores en las Listas [Si, No] y los 2 subPuntos finales del Punto 9), del PDF

**Comment by axelhzf** [comment]
El apartado 9.b -> Asignación de la categoría de empresas según la solicitud. Está resuelto.

Hay que borrar las evaluaciones actuales porque el valor se asigna al iniciarlas.

**Comment by pacomf** [comment]
Parece que ya esta todo hecho del PDF de Sole.

**Comment by smontelongo** [comment]
Las cajas de textos de los campos calculados ponerlos con fondo gris para distinguirlos mejor de los que debe introducir el usuario
El los subcriterios B1.1.\*  no colocar valor numérico en los SI/NO

**Comment by smontelongo** [comment]
Borrador en PDF:
- Poner logos
- Faltaría los comentarios de aquellos criterios que tengan comentarios, sólo se han puesto los de la evaluación
- En aquellos criterios con valores  >= no aparecen en el pdf 
- Abrir el documento pdf generado en otra página

# PDTE de preguntar a Dani 
- En la tabla Resumen sólo dejar criterios de primer nivel y total...
- ¿Cuando impedimos que se pueda modificar la evaluación, al finalizarla?? o creamos una nueva acción "Cerrar evaluación". Cuando ya la evaluación no se pueda modificar debemos generar el documento de evaluación y subirlo al expediente
- Es posible que debamos generar un documento de evaluación para el solicitante, con los criterios y comentarios que pueda ver, este documento se le hará visible en el momento de publicar la resolución provisional.

**Comment by smontelongo** [comment]
# Revisión Migración
- En la página compromisos corregir texto “Puestos de empleo a mantener”

*Al entrar como usuario en la página de presentación sigue apareciendo el botón “Obtener recibo” como si estuviera deshabilitado

*¿Podríamos cambiar el estilo de los datos numéricos para que los decimales aparecieran separados por coma y usar punto como separador de mil...?
- Cuando el área texto es de lectura en internet explorer no es posible realizar scroll

**Comment by axelhzf** [comment]
- Corregido el texto de la página de compromisos
- El botón de "Obtener recibo" está habilitado para todas los expedientes que están registrados. Todos los expedientes que migramos están registrados. Quizás probaste con un expediente de prueba que no estaba migrado. Por ejemplo, accediendo al expediente INN20101126 como usuario el botón aparece habilitado.

**Comment by axelhzf** [comment]
El cambio de los datos numéricos separados por comas no es simple. 
- Hay que cambiar en todos los sitios donde pueden aparecer un número y poner que lo formatee de esa forma. 
- Añadir un binding nuevo para decodificar de ese formato nuevo cuando lo pongan los usuarios.

Si es importante hacemos el cambio, pero nos llevará tiempo.

**Comment by pacomf** [comment]
Borrador PDF:
- Logos puestos segun la plantilla PDF del antiguo innovacion
- Los comentarios, sólo se muestran si tiene algo, es decir si están vacíos no se muestran en el PDF. **¿Es esto correcto, o hay que mostrarlos siempre?**
- Los mayores igual, y menores igual, son caracteres extendidos, por lo que el generador PDF no los reconoce. Lo que hay hecho ahora es un parser, para que los mostrara, que al generar el PDF, convierte esos caracteres a >= y <=, normales, es decir los convierte en estos 2 caracteres. Esto conlleva a analizar el texto en busca de estos caracteres extendidos para modificarlos, si los encuentra, por lo que no es eficiente que digamos. **¿Lo dejamos así, o cambiamos estos caracteres extendidos en la definición de los criterios, por <= y >=, directamente, para evitarnos el analizar el texto antes de generar el PDF**.
- Abrir el documento generado en otra pestaña, también está modificado y funcionando. Se hace un POST en JavaScript que guarda primero la pagina para despues acceder a esa información en la otra pestaña, que es la que abrira el PDF.

**FALTA lo de Pendiente de Preguntar a Dani, ¿algo nuevo respecto a esas cosas?**

**Comment by axelhzf** [comment]
Revisión de Sole:
- Permiso de sólo lectura a toda la Solicitud para que los gestores no puedan modificarla.
- Crear un rol revisor que tenga los mismos permisos que en rol gestor en la baremacion
- Aparece dos veces el mensaje de página guardada correctamente?
- Obtener PDF aparece una ventana nueva en blanco y no aparece el pdf

**Comment by pacomf** [comment]
En lo de:
- Obtener PDF aparece una ventana nueva en blanco y no aparece el pdf

¿ Me puede decir el navegador y el SO operativo utilizado cuando sucede eso?

**Comment by smontelongo** [comment]
Las pruebas las realicé con Internet explore, he probado con google Chrome y me apareció un mensaje de popUp bloquedo, al permitir elementos emergentes se abrió el documento...
¿Ha cambiado la forma de abrir lo pdfs...?, 
En cuanto a los comentarios creo que es mejor que aparezcan en una tabla diferente a la puntuación del criterio.

En cuanto al rol revisor, este ya está creado, simplemente que tenga los mismos permisos que el rol gestor en baremación

**Comment by pacomf** [comment]
Respecto a lo de los PDF:
- Al abrir los PDF, como es necesario que se abra en una nueva ventana o pestaña, y no en la misma de la aplicación, pues eso requiere utilizar JavaScript para poder conseguirlo, ya que hay que hacer un POST con los datos de la evaluacion que tiene dicha pagina, para despues en una ventana o pestaña separada, poder recuperarlos y mostrarlos en el PDF.
  JavaScript lanza la ventana como una elemento emergente, por lo que se deberá habilitar en los navegadores la propiedad de permitir elementos emergentes, para que lo haga bien.
