### ISSUE TITLE
Crear test de selenium para probar la aplicación de test

### ISSUE THREAD

**Issue by axelhzf** [FAP-Team/Fap-Module#91]
- Crear test que prueben cada una de las páginas
- Configurar los test con una base de memoria que empiece vacia

**Comment by pacomf** [comment]
Hice alguna pruebas, faltan las pruebas relacionados a los combos referenciados .. que estan fallando al guardar.

**Comment by jelcaf** [comment]
Los test ya están hechos. Pero al ejecutarlos con "auto-test" fallan por problemas con javascript del navegador que trae play interno para los tests (HtmlUnit).
